[package]
name = "db3-inspect"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0" }
thiserror = "1.0"
sc-cli = { version = "0.10.0-dev", path = "../../thirdparty/substrate/client/cli" }
sc-client-api = { version = "4.0.0-dev", path = "../../thirdparty/substrate/client/api" }
sc-executor = { version = "0.10.0-dev", path = "../../thirdparty/substrate/client/executor" }
sc-service = { version = "0.10.0-dev", default-features = false, path = "../..//thirdparty/substrate/client/service" }
sp-blockchain = { version = "4.0.0-dev", path = "../../thirdparty/substrate/primitives/blockchain" }
sp-core = { version = "6.0.0", path = "../../thirdparty/substrate/primitives/core" }
sp-runtime = { version = "6.0.0", path = "../../thirdparty/substrate/primitives/runtime" }
