[package]
name = "db3-executor"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2021"
license = "Apache-2.0"
homepage = "https://db3.network"
repository = "https://github.com/db3-teams/db3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
scale-info = { version = "2.1.1", features = ["derive"] }
frame-benchmarking = { version = "4.0.0-dev", path = "../../thirdparty/substrate/frame/benchmarking" }
db3-primitives = { version = "0.1.0", path = "../../primitives" }
db3-runtime = { version = "0.1.0", path = "../../runtime" }
sc-executor = { version = "0.10.0-dev", path = "../../thirdparty/substrate/client/executor" }
sp-core = { version = "6.0.0", path = "../../thirdparty/substrate/primitives/core" }
sp-keystore = { version = "0.12.0", path = "../../thirdparty/substrate/primitives/keystore" }
sp-state-machine = { version = "0.12.0", path = "../../thirdparty/substrate/primitives/state-machine" }
sp-tracing = { version = "5.0.0", path = "../../thirdparty/substrate/primitives/tracing" }
sp-trie = { version = "6.0.0", path = "../../thirdparty/substrate/primitives/trie" }

[features]
wasmtime = ["sc-executor/wasmtime"]
wasmi-errno = ["sc-executor/wasmi-errno"]
stress-test = []

