#! /bin/bash

mkdir -p ~/.db3/bin
mkdir -p ~/.db3/data
mkdir -p ~/.db3/logs
VERSION=v0.2.7
if [ ! -f ~/.db3/bin/db3 ]
then
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "download db3 package from github"
        wget https://github.com/dbpunk-labs/db3/releases/download/${VERSION}/db3-${VERSION}-linux-x86_64.tar.gz -O /tmp/db3-${VERSION}-linux-x86_64.tar.gz
        tar -zxf /tmp/db3-${VERSION}-linux-x86_64.tar.gz
        cp db3-${VERSION}-linux-x86_64/bin/* ~/.db3/bin
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        wget https://github.com/dbpunk-labs/db3/releases/download/${VERSION}/db3-${VERSION}-macos-x86_64.tar.gz -O /tmp/db3-${VERSION}-macos-x86_64.tar.gz
        tar -zxf /tmp/db3-${VERSION}-macos-x86_64.tar.gz
        cp db3-${VERSION}-macos-x86_64/bin/* ~/.db3/bin
    else
        echo "$OSTYPE is not supported, please give us a issue https://github.com/dbpunk-labs/db3/issues/new/choose"
        exit 1
    fi
    echo "init localnet configure"
    ~/.db3/bin/tendermint init
fi
killall db3
echo "start db3 network in single node mode..."
~/.db3/bin/db3 start -d ~/.db3/data >~/.db3/logs/db3.log 2>&1 &
sleep 2
~/.db3/bin/tendermint start >~/.db3/logs/tm.log 2>&1 &
sleep 2
echo "start db3 network ok .."
