name: Publish Package to npmjs

on: workflow_dispatch

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
      - uses: CultureHQ/actions-yarn@v1.0.1
      - run: pwd
      - run: yarn install
      - run: yarn build
      - run: npm publish
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmmirror.com/'
          path: ./src/db3js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
