name: CD
on:
    push:
        tags:
            - "[v]?[0-9]+.[0-9]+.[0-9]+"
jobs:
    npm_publish:
        name: Publish Package to npmjs
        runs-on: ubuntu-latest
        steps:
            - name: checkout db3.js
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - uses: actions/setup-node@v3.8.0
              with:
                  node-version: "16.x"
            - name: build sdk
              run: |
                TAG=${GITHUB_REF/refs\/tags\//}
                VERSION=${TAG#*v}
                echo ${VERSION}
                cd sdk && yarn version --new-version ${VERSION} && yarn && make &&  yarn build
            - uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{ secrets.NMP_TOKEN }}
                  package: ./sdk/package.json
